apiVersion: apps/v1
kind: Deployment
metadata:
 name: app-deployment
 labels:
  app: licenta-app
spec:
 replicas: 2
 selector:
  matchLabels:
   app: licenta-app
 template:
  metadata:
   name: licenta-pod
   labels:
    app: licenta-app
  spec:
   containers:
    - name: licenta-container
      image: andreir76/licenta-app
