apiVersion: v1
kind: Service
metadata:
 name: app-nodeport
 labels:
  app: licenta-app
spec:
 type: NodePort
 ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
 selector:
  app: licenta-app